### ISSUE TITLE
[FIX] BaseEntity 수정 시간 기록 방식 개선 제안

### ISSUE THREAD

**Issue by ChaeAg** [Team-WSS/WSS-Server#69]
## Description
현재 **BaseEntity**는 엔티티 수정 시 `@PreUpdate`를 통해 수정 시간(`modifiedDate`)을 자동으로 기록하고 있습니다.

하지만, 현 엔티티 설계에는 반정규화된 컬럼들이 다수 존재합니다. 예를 들어, Feed 엔티티의 좋아요 수(`likeCount`), 댓글 수(`commentCount`) 등이 있습니다. 이러한 컬럼들은 좋아요나 댓글이 추가 또는 삭제될 때 값이 수정됩니다.

문제는 이러한 반정규화된 컬럼이 변경될 때마다 Feed 엔티티의 수정 시간도 함께 갱신된다는 점인데, 이는 실제로 피드 내용이 수정된 것은 아니므로, 수정 시간이 변경되지 않아야 합니다.

이 문제를 해결하기 위해, **BaseEntity**의 수정 시간 기록 방식을 아래와 같이 변경하는 것을 제안합니다:

- **BaseEntity**는 생성 시간(`createdDate`)과 수정 시간(`modifiedDate`) 컬럼을 자동으로 갖되, 수정 시간은 `@PreUpdate`를 사용하지 않고 필요할 때 수동으로 기록하는 방식으로 변경합니다.

## To-Do
- [ ] BaseEntity의 수정 시간 기록 방식을 자동에서 수동으로 변경

<br>
@Kim-TaeUk @rinarina0429 이 이슈에 대해서 의견 남겨주시면 감사하겠습니다 😃

**Comment by Kim-TaeUk** [comment]
오!! 반정규화한 컬럼에서 문제가 발생하는 걸 깨닫다니 굿!!

아니면 테이블을 분리하는 것은 어떨까요?

**Comment by ChaeAg** [comment]
반정규화 컬럼이 제거되었으므로 해당 이슈는 상관이 없어져서 이슈 닫겠습니다!
